#!/bin/bash
# NAS Mount Manager - User Defaults
# Generated by setup.sh
# These values will be used as defaults for future installations

export NAS_MOUNT_DEFAULT_SHARES="backups"
export NAS_MOUNT_ROOT="/Users/jpierce/mnt"

# To reset to factory defaults, delete this file
# To modify defaults, edit this file or re-run setup.sh
